version: "3.5"

services:
    db:
        image: postgres
        container_name: db
        restart: always
        networks: 
            - proxynet
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        #command: >
        #    bash -c "psql -U postgres 
        #    && CREATE DATABASE studentdb;
        #    && create user studentdbuser with password 'django1234';
        #    && grant all privileges on database studentdb to studentdbuser;
        #    && create database studentdb2;
        #    && grant all privileges on database studentdb2 to studentdbuser;"
        volumes:
            - pg-data:/var/lib/postgres/data
        ports:
            - 5432:5432
networks:
    proxynet:
        name: apps-net
volumes:
    pg-data: